name: 'Test PR'
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to change base'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  actions: write
  issues: write
jobs:
  change-base:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Change base'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x
          pull_number=$(jq --raw-output .pull_request.number "${GITHUB_EVENT_PATH}")
          curl -X PATCH                                                               \
            -H "Accept: application/vnd.github+json"                                  \
            -H "Authorization: Bearer ${GITHUB_TOKEN}"                                \
            "https://api.github.com/repos/runtimeverification/contributor-test-repo/pulls/${pull_number}" \
            -d '{"base":"develop"}'

  check-and-notify:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'develop'
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Comment on PR'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Thank you for your contribution! The PR NEEDS to point to 'develop' branch, not 'master'. A maintainer will also need to approve the PR."
