name: 'Test PR'
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to change base'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read
jobs:
  check-and-notify:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref != 'develop'
    runs-on: ubuntu-24.04
    steps:
      - name: 'Comment on PR'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments" \
            -d '{"body":"Thank you for your contribution! The PR NEEDS to point to '\''develop'\'' branch, not '\''master'\''.
            A maintainer will also need to approve the PR."}'

  change-base:
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'pull_request' && contains(fromJSON('["MEMBER", "OWNER", "COLLABORATOR"]'), github.event.pull_request.author_association))
    runs-on: ubuntu-24.04
    steps:
      - name: 'Change base'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -x
          # Get PR number based on event type
          pull_number=${{ github.event_name == 'workflow_dispatch' && inputs.pr_number || github.event.pull_request.number }}
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${pull_number}" \
            -d '{"base":"develop"}'
